#! /bin/bash
#
#

CONTAINER="[scitran/afq-pipeline-3]"
echo -e "$CONTAINER  Initiated"


###############################################################################
# Built to flywheel-v0 spec.

FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input


###############################################################################
# DTIINIT

${FLYWHEEL_BASE}/run_dtiinit
exit_status=$?

if [[ $exit_status != 0 ]]; then
  echo "$CONTAINER  DTIINIT failure!"
  exit $exit_status
fi


###############################################################################
# AFQ

# Make AFQ DIRECTORY
ZIP_DIR=$INPUT_DIR/dtiInit_Archive

mkdir "$ZIP_DIR" && cp "$OUTPUT_DIR"/*.zip "$ZIP_DIR"

${FLYWHEEL_BASE}/run_afq
exit_status=$?

if [[ $exit_status != 0 ]]; then
  echo "$CONTAINER  AFQ failure!"
  exit $exit_status
fi


###############################################################################
# AFQ-BROWSER

mkdir /tmp/afq
${FLYWHEEL_BASE}/run_afq-browser.py
exit_status=$?

if [[ $exit_status != 0 ]]; then
  echo "$CONTAINER  AFQ-BROWSER failure!"
  #exit $exit_status
fi


echo "$CONTAINER  DONE!"

exit 0
